services:
  app:
    container_name: app
    build:
      context: .
      target: dev
    
    volumes:
      - .:/app
      - go-mod:/go/pkg/mod
    
    ports:
      - "${APP_PORT}:${APP_PORT}"
    
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - APP_PORT=${APP_PORT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      
    networks:
      - go-hex-network

  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: Dockerfile.db
    restart: always

    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    # These flags are required to activate the extensions
    command: 
      - "postgres"
      - "-c" 
      - "shared_preload_libraries=pg_cron,pg_partman_bgw"
      - "-c"
      - "cron.database_name=${DB_NAME}"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    ports:
      - "${DB_PORT}:${DB_PORT}"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - go-hex-network

  redis:
    container_name: hex-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

    networks:
      - go-hex-network

  nats:
    image: nats:2.10-alpine
    container_name: nats-server
    # -js: Enables JetStream
    # -sd: Defines where the stream data is stored inside the container
    # -m: Enables the monitoring port
    command: ["-js", "-sd", "/data", "-m", "8222"]
    ports:
      - "4222:4222" # Standard NATS client port
      - "8222:8222" # HTTP Monitoring/Management port
    volumes:
      - nats_storage:/data
    restart: always

    networks:
      - go-hex-network

networks:
  go-hex-network:
    driver: bridge 

volumes:
  go-mod:
  postgres-data:
  redis_data:
  nats_storage:
